import { geometry4326 } from '$lib/server/db/geometry';
import { sql } from 'drizzle-orm';
import { file } from '$lib/server/db/schema';
import {
	customType,
	index,
	integer,
	jsonb,
	pgTable,
	primaryKey,
	text,
	timestamp,
	unique,
	uuid
} from 'drizzle-orm/pg-core';
import type { NoteContent } from './content';
import type { FeatureKind } from './map/geometry';

// Mirror of migrations/0005_notes_init.sql and 0006_notes_map_feature.sql. The SQL files are the
// source of truth.

function timestamptz(name: string) {
	return timestamp(name, { withTimezone: true });
}

const tsvector = customType<{ data: string }>({ dataType: () => 'tsvector' });

export const note = pgTable(
	'note',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		title: text('title').notNull().default(''),
		content: jsonb('content').$type<NoteContent>().notNull(),
		contentText: text('content_text').notNull().default(''),
		version: integer('version').notNull().default(1),
		deletedAt: timestamptz('deleted_at'),
		createdAt: timestamptz('created_at').defaultNow().notNull(),
		updatedAt: timestamptz('updated_at').defaultNow().notNull(),
		// Generated by the database from the title and the text; never written.
		searchVector: tsvector('search_vector').generatedAlwaysAs(
			sql`setweight(to_tsvector('simple', title), 'A') || setweight(to_tsvector('simple', left(content_text, 200000)), 'B')`
		)
	},
	(table) => [
		index('note_updated_at_idx').on(table.updatedAt.desc()),
		index('note_deleted_at_idx').on(table.deletedAt)
	]
);

export const noteRevision = pgTable(
	'note_revision',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		noteId: uuid('note_id')
			.notNull()
			.references(() => note.id, { onDelete: 'cascade' }),
		version: integer('version').notNull(),
		title: text('title').notNull(),
		content: jsonb('content').$type<NoteContent>().notNull(),
		actorType: text('actor_type').$type<'owner' | 'api_key' | 'system'>().notNull(),
		actorId: text('actor_id'),
		createdAt: timestamptz('created_at').defaultNow().notNull(),
		updatedAt: timestamptz('updated_at').defaultNow().notNull()
	},
	(table) => [unique('note_revision_note_version_unique').on(table.noteId, table.version)]
);

export const noteFile = pgTable(
	'note_file',
	{
		noteId: uuid('note_id')
			.notNull()
			.references(() => note.id, { onDelete: 'cascade' }),
		fileId: uuid('file_id')
			.notNull()
			.references(() => file.id, { onDelete: 'cascade' })
	},
	(table) => [
		primaryKey({ columns: [table.noteId, table.fileId] }),
		index('note_file_file_id_idx').on(table.fileId)
	]
);

export const mapFeature = pgTable(
	'map_feature',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		noteId: uuid('note_id')
			.notNull()
			.references(() => note.id, { onDelete: 'cascade' }),
		geometry: geometry4326('geometry').notNull(),
		kind: text('kind').$type<FeatureKind>().notNull(),
		createdAt: timestamptz('created_at').defaultNow().notNull(),
		updatedAt: timestamptz('updated_at').defaultNow().notNull()
	},
	(table) => [
		index('map_feature_geometry_idx').using('gist', table.geometry),
		index('map_feature_note_id_idx').on(table.noteId)
	]
);
